name: CI/CD Pipeline for Spring PetClinic

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"
  ECR_URL: "014498631401.dkr.ecr.us-east-1.amazonaws.com"
  IMAGE_TAG: "${{ github.sha }}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code (for deployment purposes)
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up AWS Credentials
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Deploy to EC2
    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
        docker pull $ECR_URL/spring-petclinic:$IMAGE_TAG
        docker stop petclinic || true
        docker rm petclinic || true
        docker run -d -p 80:8080 --name petclinic $ECR_URL/spring-petclinic:$IMAGE_TAG
        EOF
