name: CI/CD Pipeline for Spring PetClinic

# Trigger the workflow when code is pushed to the 'main' branch
on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-1"
  ECR_URL: "014498631401.dkr.ecr.us-east-1.amazonaws.com"
  IMAGE_TAG: "${{ github.sha }}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 3: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t $ECR_URL/spring-petclinic:$IMAGE_TAG .

    # Step 4: Push Docker Image to ECR
    - name: Push Docker Image
      run: |
        docker push $ECR_URL/spring-petclinic:$IMAGE_TAG

    # Step 5: Deploy to EC2
    - name: Deploy to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$EC2_SSH_KEY" > ec2-key.pem
        chmod 400 ec2-key.pem
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
        docker pull $ECR_URL/spring-petclinic:$IMAGE_TAG
        docker stop petclinic || true
        docker rm petclinic || true
        docker run -d -p 80:8080 --name petclinic $ECR_URL/spring-petclinic:$IMAGE_TAG
        EOF
